#!/bin/bash

set -e

DIE=0
_pwd="$(pwd)"
as_me="$(basename $0)"

(autoconf --version) < /dev/null > /dev/null 2>&1 || {
    echo
    echo "You must have autoconf installed to run $as_me."
    echo "Download the appropriate package for your distribution,"
    echo "or see http://www.gnu.org/software/autoconf"
    DIE=1
}

(libtoolize --version) < /dev/null > /dev/null 2>&1 || {
	echo
	echo "You must have libtool installed to run $as_me."
	echo "Download the appropriate package for your distribution,"
	echo "or see http://www.gnu.org/software/libtool"
	DIE=1
}

(automake --version) < /dev/null > /dev/null 2>&1 || {
    echo
    echo "You must have automake installed to run $as_me."
    echo "Download the appropriate package for your distribution,"
    echo "or see http://www.gnu.org/software/automake"
    DIE=1
}

if [ "$DIE" -eq 1 ]; then
    exit 1
fi 

_author="Shusheng Shao"
_email="iblackangel@163.com"

lt_current="1"
lt_revision="0"
lt_age="0"

_package_name="$(basename $PWD)"
_name=$(echo ${_package_name} | sed 's/lib//')
_package_version="${lt_current}.${lt_revision}.${lt_age}"
_package_bug_report_email=${_email}

makefile_am="Makefile.am"
configure_ac="configure.ac"
configure_scan="configure.scan"
as_nl='
'
export as_nl

_lt_package_name="${_package_name}_la"
_pkgconfig="${_package_name}.pc"
_pkgconfig_in="${_pkgconfig}.in"

content="\
lib_LTLIBRARIES = ${_package_name}.la

# library version
${_lt_package_name}_LDFLAGS=\$(LTLDFLAGS)

######################################
# Cflags and Libs
# ${_lt_package_name}_CXXFLAGS = \$(LIBICONV_CFLAGS)
# ${_lt_package_name}_LIBADD = \$(LIBICONV_LIBS)

${_lt_package_name}_SOURCES = \\"

header_content="\
include_HEADERS = \\"

top_dir_content="\
SUBDIRS=src
ACLOCAL_AMFLAGS=-I m4
DISTCLEANFILES=${_pkgconfig}

pkgconfigdir=\$(libdir)/pkgconfig
pkgconfig_DATA=${_pkgconfig}"

pc_in_content="\
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@

Name: ${_package_name}
Description: C API for ${_package_name}
Version: @VERSION@
Libs: -L\${libdir} -l${_name}
Cflags: -I\${includedir}"

# scan cpp files
scan_cpp_file () {
    find . -name "*.cpp" -print			\
    | sed 's|\./||'				\
    | sed '1,$s|cpp$|cpp    \\|'		\
    | sed '$s/\\$//'
}

# scan header files
scan_hpp_file () {
    find . -name "*.h" -print			\
    | sed 's|\./||'				\
    | sed '1,$s|h$|&    \\|'			\
    | sed '$s/\\$//'
}

as_fn_set_status () {
    return $1
}

as_fn_exit () {
    set +e
    as_fn_set_status $1
    exit $1
}

as_fn_error () {
    as_status=$1; test $as_status -eq 0 && as_status=1
    echo "$as_me: error: $2" >&2
    as_fn_exit $as_status
}

#########################################################
#
# Main body of script.
#
#########################################################
usage="\
Usage: `basename $0` [OPTION]...

Generate configure.ac and Makefile.am files, then auto configure it.

Operation modes:
  -h, --help        print this help, then exit
  -V, --version     print version number, then exit
"

help="\
Try \`$as_me --help' for more information."

version="\
autobuild (Blackangel) 1.0
Copyright (C) 2015 $_author <${_email}>"

while test $# -gt 0 ; do
    option=`expr "x$1" : 'x\(--[^=]*\)' \| \
                 "x$1" : 'x\(-.\)'`
    optarg=`expr "x$1" : 'x--[^=]*=\(.*\)' \| \
                 "x$1" : 'x-.\(.*\)'`
    case $1 in
	--version | -V )
	    echo "$version" ; exit ;;
	--help | -h )
	    echo "$usage" ; exit ;;
	-- )  # Stop option processing
	    shift ; break ;;
	- ) # Use stdin as input
	    break ;;
	-* )
	    exec >&2
	    as_fn_error $? "invalid option \`$1'$as_nl$help" ;;
	* )
	    break ;;
    esac
done

build_src_dir_makefile_am() {
    echo "$content" > $makefile_am
    scan_cpp_file >> $makefile_am

    header_files_count=$(find . -name "*.h" | wc -l)
    if [ $header_files_count -gt 0 ]; then
	echo "$as_nl$header_content" >> $makefile_am
	scan_hpp_file >> $makefile_am
    fi
}

build_header_makefile_am() {
    if [ $(find . -name "*.h" | wc -l) -gt 0 ]; then
	echo "$header_content" > $makefile_am
	scan_hpp_file >> $makefile_am
    fi
}

build_top_dir_makefile_am() {
    echo "$top_dir_content" > $makefile_am
    if [ -d $_pwd/include ]; then
	sed -i "1s/src/& include/" $makefile_am
    fi
}

build_pkgconfig() {
    echo "${pc_in_content}" > $_pkgconfig_in
}

if [ -d $_pwd/src ];then
    cd $_pwd/src
    build_src_dir_makefile_am
else
    { echo "There is no \`src' direcoty." ; exit 1; }
fi

if [ -d $_pwd/include ]; then
    cd $_pwd/include
    build_header_makefile_am
fi

cd $_pwd
build_top_dir_makefile_am
build_pkgconfig

autoscan
sed -i "s/FULL-PACKAGE-NAME/${_package_name}/" $configure_scan
sed -i "s/VERSION/${_package_version}/" $configure_scan
sed -i "s/BUG-REPORT-ADDRESS/${_package_bug_report_email}/" $configure_scan
sed -i "/AC_CONFIG_HEADERS/a AM_INIT_AUTOMAKE([-Wall -Werror foreign])" \
$configure_scan
sed -i "/AC_CONFIG_HEADERS/a AC_CONFIG_MACRO_DIR([m4])" $configure_scan
sed -i "/AC_PROG_CC/a AM_PROG_AR" $configure_scan
sed -i "/AM_PROG_AR/a AC_PROG_LIBTOOL" $configure_scan

sed -i "/programs/i lt_current=\"1\"" $configure_scan
sed -i "/programs/i lt_revision=\"0\"" $configure_scan
sed -i "/programs/i lt_age=\"0\"" $configure_scan
sed -i "/programs/i LTLDFLAGS=\"-version-info \${lt_current}:\${lt_revision}:\${lt_age}\"" $configure_scan
sed -i "/programs/i AC_SUBST(LTLDFLAGS)" $configure_scan
sed -i "/programs/i \ " $configure_scan
sed -i "/libraries/a # PKG_CHECK_MODULES([HELLO], [libhello >= 1.0])" $configure_scan
sed -i "/libraries/a # Add bellow content if you need to link with another library" $configure_scan
sed -i "/AC_OUTPUT/i AC_CONFIG_FILES([${_pkgconfig}])" $configure_scan
mv $configure_scan $configure_ac

[ $? -eq 0 ] && libtoolize --copy --install --force && autoreconf -if
