#!/bin/sh

PATH=/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

do_start() {
    exec xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' 1
}

do_stop() {
    exec xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' 0
}

case "$1" in
    start)
	do_start
	;;
    restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
    stop)
	do_stop
	;;
    *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
